brand:
  handles: ["Send"]  # Twitter handles to monitor (without @)

filters:
  lang: "en"  # Language filter for tweets (en, es, fr, de, etc.)
  time_range_hours: 6  # How many hours back to search (start with 2-6 for testing)

notify:
  slack_channel: "#social-monitoring"  # Slack channel for notifications