name: Brand Listener - Generate Reports

on:
  push:
    branches:
      - main
    paths:
      - 'apps/twitter-listener/src/reporting.ts'
      - 'packages/reporting/**'
      - 'packages/core/src/services/**'
  workflow_dispatch: # Allow manual triggering
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean
      top_k:
        description: 'Number of top tweets to include in report'
        required: false
        default: '5'
        type: string

jobs:
  run-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Clean previous builds
        run: pnpm run clean

      - name: Build packages
        run: pnpm run build

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "❌ SLACK_WEBHOOK_URL secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Generate and send reports
        working-directory: apps/twitter-listener
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          NODE_ENV: production
          DEBUG: ${{ inputs.debug }}
          TOP_K: ${{ inputs.top_k || '5' }}
        run: |
          echo "📊 Starting Brand Listener Reports..."
          echo "Timestamp: $(date -u)"
          echo "Working directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "Pnpm version: $(pnpm --version)"
          echo "GCP Authentication: Configured via google-github-actions/auth"
          echo "Debug mode: ${{ inputs.debug }}"
          echo "Top K tweets: ${{ inputs.top_k || '5' }}"
          echo ""
          npx tsx src/reporting.ts

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: brand-listener-reports-logs-${{ github.run_number }}
          path: |
            apps/twitter-listener/.state/
            apps/twitter-listener/logs/
            apps/twitter-listener/dist/
          retention-days: 7
          if-no-files-found: ignore

      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: |
            🚨 Brand Listener Reports failed!
            
            **Details:**
            - Run: ${{ github.run_number }}
            - Time: ${{ github.event.head_commit.timestamp }}
            - View logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
