name: Brand Listener - Ingest Data and Reply to Tweets

on:
  push:
    branches:
      - main
    paths:
      - 'apps/twitter-listener/**'
      - 'packages/**'
  schedule:
    # Run every 6 hours starting at 00:00 UTC (00:00, 06:00, 12:00, 18:00)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  run-brand-listener:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Clean previous builds
        run: pnpm run clean

      - name: Build packages
        run: pnpm run build

      - name: Validate required secrets
        run: |
          missing_secrets=()
          
          if [ -z "${{ secrets.TWITTER_USERNAME }}" ]; then
            missing_secrets+=("TWITTER_USERNAME")
          fi

          if [ -z "${{ secrets.TWITTER_API_KEY }}" ]; then
            missing_secrets+=("TWITTER_API_KEY")
          fi
          
          if [ -z "${{ secrets.OPENROUTER_API_KEY }}" ]; then
            missing_secrets+=("OPENROUTER_API_KEY")
          fi
          
          if [ -z "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            missing_secrets+=("SLACK_WEBHOOK_URL")
          fi
          
          if [ ${#missing_secrets[@]} -gt 0 ]; then
            echo "❌ Missing required secrets: ${missing_secrets[*]}"
            exit 1
          fi
          
          echo "✅ All required secrets are configured"

      - name: Run main brand listener
        working-directory: apps/twitter-listener
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          NODE_ENV: production
          DEBUG: ${{ inputs.debug }}
        run: |
          echo "🚀 Starting Brand Listener Main Process..."
          echo "Timestamp: $(date -u)"
          echo "Working directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "Pnpm version: $(pnpm --version)"
          echo "GCP Authentication: Configured via google-github-actions/auth"
          echo "Debug mode: ${{ inputs.debug }}"
          echo ""
          npx tsx src/index.ts

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: brand-listener-main-logs-${{ github.run_number }}
          path: |
            apps/twitter-listener/.state/
            apps/twitter-listener/logs/
            apps/twitter-listener/dist/
          retention-days: 7
          if-no-files-found: ignore

      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: |
            🚨 Brand Listener Main Process failed!
            
            **Details:**
            - Run: ${{ github.run_number }}
            - Time: ${{ github.event.head_commit.timestamp }}
            - View logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
